const users: any[] = [
  {
    _id: "67af9b8028164668d0c25c38",
    username: "abbas",
    password: "111111",
    email: "abbas@gmail.com",
    fullname: "Abbas Moqaddam",
    followers: [],
    following: [],
    profilePicture: "/uploads/1.jpg",
    bio: "This is a test paragraph for biography field",
  },
  {
    _id: "67af9b8028164668d0c25c39",
    username: "amir",
    password: "111111",
    email: "amir@gmail.com",
    fullname: "Amir Moqaddam",
    followers: [],
    following: [],
    profilePicture: "/uploads/2.jpg",
    bio: "This is a test paragraph for biography field",
  },
  {
    _id: "67af9b8028164668d0c25c40",
    username: "ahmad",
    password: "111111",
    email: "ahmad@gmail.com",
    fullname: "Ahmad Moosavi",
    followers: [],
    following: [],
    profilePicture: "/uploads/3.jpg",
    bio: "This is a test paragraph for biography field",
  },
  {
    _id: "67af9b8028164668d0c25c41",
    username: "zahra",
    password: "111111",
    email: "zahra@gmail.com",
    fullname: "Zahra Samimi",
    followers: [],
    following: [],
    profilePicture: "/uploads/4.jpg",
    bio: "This is a test paragraph for biography field",
  },
  {
    _id: "67af9b8028164668d0c25c42",
    username: "mohammad",
    password: "111111",
    email: "mohammad@gmail.com",
    fullname: "Mohammad Moosavi",
    followers: [],
    following: [],
    profilePicture: "/uploads/5.jpg",
    bio: "This is a test paragraph for biography field",
  },
  {
    _id: "67af9b8028164668d0c25c43",
    username: "farhad",
    password: "111111",
    email: "farhad@gmail.com",
    fullname: "Farhad Vahidi",
    followers: [],
    following: [],
    profilePicture: "/uploads/6.jpg",
    bio: "This is a test paragraph for biography field",
  },
  {
    _id: "67af9b8028164668d0c25c44",
    username: "saeed",
    password: "111111",
    email: "saeed@gmail.com",
    fullname: "Saeed Heaydari",
    followers: [],
    following: [],
    profilePicture: "/uploads/7.jpg",
    bio: "This is a test paragraph for biography field",
  },
  {
    _id: "67af9b8028164668d0c25c45",
    username: "sara",
    password: "111111",
    email: "sara@gmail.com",
    fullname: "Sara Mohammadi",
    followers: [],
    following: [],
    profilePicture: "/uploads/8.jpg",
    bio: "This is a test paragraph for biography field",
  },
  {
    _id: "67af9b8028164668d0c25c46",
    username: "nahid",
    password: "111111",
    email: "nahid@gmail.com",
    fullname: "Nahid Roshani",
    followers: [],
    following: [],
    profilePicture: "/uploads/9.jpg",
    bio: "This is a test paragraph for biography field",
  },
  {
    _id: "67af9b8028164668d0c25c47",
    username: "farzad",
    password: "111111",
    email: "farzad@gmail.com",
    fullname: "Farzad Hosseini",
    followers: [],
    following: [],
    profilePicture: "/uploads/10.jpg",
    bio: "This is a test paragraph for biography field",
  },
  {
    _id: "67af9b8028164668d0c25c48",
    username: "yaser",
    password: "111111",
    email: "yaser@gmail.com",
    fullname: "Yaser Hamidi",
    followers: [],
    following: [],
    profilePicture: "/uploads/11.jpg",
    bio: "This is a test paragraph for biography field",
  },
  {
    _id: "67af9b8028164668d0c25c49",
    username: "saber",
    password: "111111",
    email: "saber@gmail.com",
    fullname: "Saber Karimi",
    followers: [],
    following: [],
    profilePicture: "/uploads/12.jpg",
    bio: "This is a test paragraph for biography field",
  },
  {
    _id: "67af9b8028164668d0c25c50",
    username: "hamid",
    password: "111111",
    email: "hamid@gmail.com",
    fullname: "Hamid Yusefi",
    followers: [],
    following: [],
    profilePicture: "/uploads/13.jpg",
    bio: "This is a test paragraph for biography field",
  },
  {
    _id: "67af9b8028164668d0c25c51",
    username: "vahid",
    password: "111111",
    email: "vahid@gmail.com",
    fullname: "Vahid Jabbari",
    followers: [],
    following: [],
    profilePicture: "/uploads/14.jpg",
    bio: "This is a test paragraph for biography field",
  },
  {
    _id: "67af9b8028164668d0c25c52",
    username: "reza",
    password: "111111",
    email: "reza@gmail.com",
    fullname: "Reza Kazemi",
    followers: [],
    following: [],
    profilePicture: "/uploads/15.jpg",
    bio: "This is a test paragraph for biography field",
  },
  {
    _id: "67af9b8028164668d0c25c53",
    username: "mina",
    password: "111111",
    email: "mina@gmail.com",
    fullname: "Mina Karami",
    followers: [],
    following: [],
    profilePicture: "/uploads/16.jpg",
    bio: "This is a test paragraph for biography field",
  },
  {
    _id: "67af9b8028164668d0c25c54",
    username: "kazem",
    password: "111111",
    email: "kazem@gmail.com",
    fullname: "Kazem Dashti",
    followers: [],
    following: [],
    profilePicture: "/uploads/17.jpg",
    bio: "This is a test paragraph for biography field",
  },
  {
    _id: "67af9b8028164668d0c25c55",
    username: "homa",
    password: "111111",
    email: "homa@gmail.com",
    fullname: "Homa Farhadi",
    followers: [],
    following: [],
    profilePicture: "/uploads/18.jpg",
    bio: "This is a test paragraph for biography field",
  },
  {
    _id: "67af9b8028164668d0c25c56",
    username: "fazel",
    password: "111111",
    email: "fazel@gmail.com",
    fullname: "Fazel Pezeshki",
    followers: [],
    following: [],
    profilePicture: "/uploads/19.jpg",
    bio: "This is a test paragraph for biography field",
  },
  {
    _id: "67af9b8028164668d0c25c57",
    username: "arash",
    password: "111111",
    email: "arash@gmail.com",
    fullname: "Arash Bayat",
    followers: [],
    following: [],
    profilePicture: "/uploads/20.jpg",
    bio: "This is a test paragraph for biography field",
  },
  {
    _id: "67af9b8028164668d0c25c58",
    username: "kaveh",
    password: "111111",
    email: "kaveh@gmail.com",
    fullname: "Kaveh Rayegan",
    followers: [],
    following: [],
    profilePicture: "/uploads/21.jpg",
    bio: "This is a test paragraph for biography field",
  },
  {
    _id: "67af9b8028164668d0c25c59",
    username: "raha",
    password: "111111",
    email: "raha@gmail.com",
    fullname: "Raha Saberi",
    followers: [],
    following: [],
    profilePicture: "/uploads/22.jpg",
    bio: "This is a test paragraph for biography field",
  },
  {
    _id: "67af9b8028164668d0c25c60",
    username: "akbar",
    password: "111111",
    email: "akbar@gmail.com",
    fullname: "Akbar Rezayi",
    followers: [],
    following: [],
    profilePicture: "/uploads/23.jpg",
    bio: "This is a test paragraph for biography field",
  },
  {
    _id: "67af9b8028164668d0c25c61",
    username: "yunes",
    password: "111111",
    email: "yunes@gmail.com",
    fullname: "Yunes Sarvi",
    followers: [],
    following: [],
    profilePicture: "/uploads/24.jpg",
    bio: "This is a test paragraph for biography field",
  },
  {
    _id: "67af9b8028164668d0c25c62",
    username: "mohsen",
    password: "111111",
    email: "mohsen@gmail.com",
    fullname: "Mohsen Marvi",
    followers: [],
    following: [],
    profilePicture: "/uploads/25.jpg",
    bio: "This is a test paragraph for biography field",
  },
  {
    _id: "67af9b8028164668d0c25c63",
    username: "mahin",
    password: "111111",
    email: "mahin@gmail.com",
    fullname: "Mahin Kasravi",
    followers: [],
    following: [],
    profilePicture: "/uploads/26.jpg",
    bio: "This is a test paragraph for biography field",
  },
  {
    _id: "67af9b8028164668d0c25c64",
    username: "mehran",
    password: "111111",
    email: "mehran@gmail.com",
    fullname: "Mehran Bayat",
    followers: [],
    following: [],
    profilePicture: "/uploads/27.jpg",
    bio: "This is a test paragraph for biography field",
  },
  {
    _id: "67af9b8028164668d0c25c65",
    username: "asqar",
    password: "111111",
    email: "asqar@gmail.com",
    fullname: "Asqar fazeli",
    followers: [],
    following: [],
    profilePicture: "/uploads/28.jpg",
    bio: "This is a test paragraph for biography field",
  },
  {
    _id: "67af9b8028164668d0c25c66",
    username: "ebrahim",
    password: "111111",
    email: "ebrahim@gmail.com",
    fullname: "Ebrahim Harandi",
    followers: [],
    following: [],
    profilePicture: "/uploads/29.jpg",
    bio: "This is a test paragraph for biography field",
  },
  {
    _id: "67af9b8028164668d0c25c67",
    username: "firooz",
    password: "111111",
    email: "firooz@gmail.com",
    fullname: "Firooz Farhadi",
    followers: [],
    following: [],
    profilePicture: "/uploads/30.jpg",
    bio: "This is a test paragraph for biography field",
  },
  {
    _id: "67af9b8028164668d0c25c68",
    username: "sima",
    password: "111111",
    email: "sima@gmail.com",
    fullname: "Sima Sabet",
    followers: [],
    following: [],
    profilePicture: "/uploads/31.jpg",
    bio: "This is a test paragraph for biography field",
  },
];

for (let i = 0; i < users.length; i++) {
  for (let j = 0; j < users.length; j++) {
    if (i !== j && Math.random() > 0.4) {
      users[j].followers.push(users[i]._id);
      users[i].following.push(users[j]._id);
    }
  }
}

const posts: any[] = [];

for (let i = 256; i < 1000; i++) {
  const _id = "67c98e4e7cbe52d589bf3" + i.toString(16);
  const likes = [];
  for (let u of users) {
    if (Math.random() > 0.5) {
      likes.push(u._id);
    }
  }
  const user = Math.floor(Math.random() * users.length);
  const n = (i % 51) + 1;
  posts.push({
    _id,
    caption: ("Test Caption " + (i - 256) + " , ").repeat(Math.ceil(Math.random() * 20) + 4),
    image: "/uploads/" + n + ".jpg",
    user: users[user]._id,
    likes,
    comments: [],
    createdAt: Date.now() - Math.ceil(Math.random() * 864000000),
    updatedAt: Date.now() - Math.ceil(Math.random() * 864000000),
  });
}

for (let i = 1; i < 2000; i++) {
  const user = Math.floor(Math.random() * users.length);
  const post = Math.floor(Math.random() * posts.length);
  const comment = {
    text: "Test Comment " + i,
    user: users[user]._id,
  };
  posts[post].comments.push(comment);
}

export { users, posts };
